### ISSUE TITLE
目前是需要将代码库传到github上然后在使用chatgpt的api才可以吗

### ISSUE THREAD

**Issue by ccly1996** [unit-mesh/unit-gen#4]

**Comment by phodal** [comment]
不需要

**Comment by ccly1996** [comment]
那咱们的项目路径在哪配置啊，我看手册里配的github地址

---- 回复的原邮件 ----
| 发件人 | Fengda ***@***.***> |
| 发送日期 | 2024年03月19日 14:50 |
| 收件人 | unit-mesh/unit-gen ***@***.***> |
| 抄送人 | ccly1996 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [unit-mesh/unit-gen] 目前是需要将代码库传到github上然后在使用chatgpt的api才可以吗 (Issue #4) |

不需要

**Comment by phodal** [comment]
理论上把  repository  改成本地路径就行了：

https://github.com/unit-mesh/unit-gen/tree/master/examples/config-examples/
