### ISSUE TITLE
Missing SimpleCodePicker in Java API example

### ISSUE THREAD

**Issue by tdsnxchen-max** [unit-mesh/unit-gen#6]
在Java API example里面使用了SimpleCodePicker这个类，但是我们在项目里面并没有找到这个类,请看一下这个问题如何处理？
![image](https://github.com/unit-mesh/unit-gen/assets/166463439/6ac3f7d5-c026-4f3e-9256-2f565fc449b3)

**Comment by phodal** [comment]
应该是 API 变了，参考一下：https://github.com/unit-mesh/unit-gen/blob/master/unit-gen/src/main/kotlin/cc/unitmesh/runner/Picker.kt

**Comment by tdsnxchen-max** [comment]
如果可以的话，最好把这里更新一下，我看到SimpleCodePicker是v0.1.7版本的内容了。
