### ISSUE TITLE
Is the UnitGen support TypeScript/JavaScript?

### ISSUE THREAD

**Issue by LeoLiuYan** [unit-mesh/unit-gen#8]
HI， @phodal 
As the title said, does the UnitGen support `TypeScript` and `JavaScript` language to generate data from existing codebase ?

**Comment by phodal** [comment]
yes

**Comment by LeoLiuYan** [comment]
What's the UnitGen's Q3 roadmap?   @phodal

**Comment by phodal** [comment]
No roadmap for now
